name: PR Title Validation

on: [pull_request]

jobs:
  comment:
    runs-on: ubuntu-latest
    if: (!startsWith(github.event.pull_request.title, 'PR - '))
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const request = {
              pull_number: github.context.payload.pull_request.number,
              body: 'Test Body Update'
            }
            const octokit = github.getOctokit(inputs.token)
            const response = await octokit.pulls.update(request)
            console.log("Coucou a marche!")
